version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'Github Actions'
      - 'dependencies'

  # Maintain dependencies for yarn
  - package-ecosystem: 'npm' # We need to specify npm, although we use yarn, see https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
    labels:
      - 'yarn'
      - 'dependencies'

  - package-ecosystem: 'npm' # We need to specify npm, although we use yarn, see https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
    directory: '/example/'
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
    labels:
      - 'yarn'
      - 'dependencies'

